env:
  browser: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 6

# plugins:
#   - import

extends:
  - eslint:all
  # https://prettier.io/docs/en/integrating-with-linters.html
  - plugin:prettier/recommended

# THIS RULES ARE ORGANIZED AS IN THE PAGE https://eslint.org/docs/rules/
rules:
  # ============================================================================
  # Strict Mode
  # ============================================================================

  # This rule requires or disallows strict mode directives.
  # global: requires one strict mode directive in the global scope (and disallows any other strict mode directives)
  strict:
    - error
    - global

  # ============================================================================
  # Stylistic Issues
  # ============================================================================
  capitalized-comments: off
  indent:
    - error
    - 2

  max-statements:
    - error
    - max: 20
    # Does not work with IIFE
    # https://github.com/eslint/eslint/issues/12950
    - ignoreTopLevelFunctions: true

  max-lines-per-function:
    - error
    - max: 60

  lines-around-comment: off

  no-ternary: off

  # enforce variables to be declared either together or separately in functions
  # [when we declare several array functions in a file, give an error]
  one-var: off

  # Give use false-positive into ./site/themes/sogilis/static/js/scripts.js
  padded-blocks: off

  quotes:
    - error
    - single

  wrap-iife:
    - error
    - inside
