baseurl = "/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Sogilis blog Site"
theme = "sogilis"
enableEmoji = true
debug = true
paginate = 999
disqusShortname = "sogilisblog"

[languages.fr]
  languageName = "Français"

  [languages.fr.params]
    twitter = "https://twitter.com/Sogilis?lang=fr"
    linkedin = "https://www.linkedin.com/company/sogilis/"
