baseurl = "/"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
title = "Sogilis blog Site"
theme = "sogilis"
enableEmoji = true
debug = true
paginate = 999

[params]
  disqus = "trololu"

[languages.en]
  baseURL = "https://blog.sogilis.com"
  languageName = "English"

  [languages.en.params]
    twitter = "https://twitter.com/Sogilis?lang=en"
    linkedin = "https://www.linkedin.com/company/sogilis/"
    dateFormat = "January 2 2006"


[languages.fr]
  baseURL = "https://blog.sogilis.fr"
  languageName = "Français"

  [languages.fr.params]
    twitter = "https://twitter.com/Sogilis?lang=fr"
    linkedin = "https://www.linkedin.com/company/sogilis/"
