baseurl = "/"
languageCode = "fr"
title = "Sogilis blog Site"
theme = "sogilis"
enableEmoji = true
debug = true

[params]
  disqus = "trololu"

[languages.en]
  languageName = "English"

  [languages.en.params]
    twitter = "https://twitter.com/Sogilis?lang=en"
    linkedin = "https://www.linkedin.com/company/sogilis/"

[languages.fr]
  languageName = "Français"

  [languages.fr.params]
    twitter = "https://twitter.com/Sogilis?lang=fr"
    linkedin = "https://www.linkedin.com/company/sogilis/"
