baseurl = "/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Blog Site"
theme = "sogilis"
enableEmoji = true
debug = true
paginate = 999
disqusShortname = "sogilisblog"
enableRobotsTXT = true

[params]
  siteDescription = "Série d'articles écrits par les membres de Sogilis décrivants la vie en entreprise ou des sujets techniques précis"

[languages.fr]
  languageName = "Français"

  [languages.fr.params]
    twitter = "https://twitter.com/Sogilis?lang=fr"
    linkedin = "https://www.linkedin.com/company/sogilis/"
