baseurl = "/"
languageCode = "fr"
title = "Sogilis blog Site"
theme = "sogilis"
enableEmoji = true
debug = true

[params]
  disqus = "trololu"

[blackfriday]
  taskLists = true
  smartypants = true
  angledQuotes = true
  fencedCode = true
  extensions = ["tables"]
  plainIDAnchors = true
