<template>
  <article id="articlepage">
    <section id="articlepage-header">
      <!-- Illustration -->
      <span id="articlepage-header-img-container">
        <img
          id="articlepage-header-img"
          class="articlepage-img"
          :src="
            $frontmatter.image
              ? $frontmatter.image
              : '/img/blog_preview_default.jpg'
          "
          :alt="
            $frontmatter.imgTestAlt
              ? $frontmatter.imgTestAlt
              : 'Illustration de l\'article'
          "
        />
      </span>

      <div id="articlepage-header-title">
        <h1 class="title article-title">{{ $frontmatter.title }}</h1>
        <div class="articlepage-header-title-details">
          <ul v-for="tag in $frontmatter.tags" :key="tag" class="tags-list">
            <li class="tag">
              <RouterLink :to="'/tags/' + tag">{{ tag }}</RouterLink>
            </li>
          </ul>
          <div>
            <ul v-for="category in $frontmatter.categories" :key="category">
              <li>
                <RouterLink :to="'/categories/' + category">{{
                  category
                }}</RouterLink>
              </li>
            </ul>
            Écrit par
            <template v-if="$frontmatter.author">
              {{ $frontmatter.author }}
            </template>
            <template v-else> Sogilis </template>
            <br />
            Publié le
            {{ getDate($frontmatter.date) }}
            <br />
            Read time {{ $page.readingTime.minutes }} minutes
          </div>
        </div>
      </div>
    </section>

    <section id="articlepage-content">
      <Content />
    </section>

    <img
      id="articlepage-img-bottom"
      class="articlepage-img"
      :src="
        $frontmatter.image
          ? $frontmatter.image
          : '/img/blog_preview_default.jpg'
      "
      :alt="
        $frontmatter.imgTestAlt
          ? $frontmatter.imgTestAlt
          : 'Illustration de l\'article'
      "
    />

    <section id="articlepage-comments">
      <i>Pas de commentaire pour l'instant</i>
    </section>
    <br />
    <br />
    <br />
    &nbsp;
  </article>
</template>

<script>
import { getDateInEnglish } from '../utils/date';

export default {
  methods: {
    getDate(date) {
      return getDateInEnglish(date);
    },
  },
};
</script>

<style lang="css">
/*
  can't be scopped because all HTML elements generated by VuePress are out of
  scop of the current Component
  TODO: extract
*/
#articlepage {
  margin-bottom: 5rem;
  display: flex;
  flex-direction: column;
  max-width: inherit;
  color: var(--color-black-mine-shaft);
  font-size: 16px;
  line-height: 1.5;
}

#articlepage {
  max-width: 42.5rem;
  margin: 0 auto;
}

#articlepage-content a {
  color: var(--wolf-blue);
  transition: color 0.3s;
}

#articlepage-content a:hover {
  color: var(--dark-grey);
}

#articlepage p {
  margin-bottom: 1.5em;
  hyphens: auto;
}

/* Section header */
/* ========================================================================== */
#articlepage-header {
  display: flex;
  flex-direction: column;
  margin-bottom: 3rem;
  word-wrap: break-word;
}

#articlepage-header-img-container {
  width: 100%;
  margin-bottom: 1em;
}

@media (min-width: 992px) {
  #articlepage-header {
    flex-direction: row;
  }

  #articlepage-header-img-container {
    width: 70%;
    margin-bottom: 0;
  }
}

.articlepage-header-title-details {
  margin-left: 1.6rem;
}

/* Section content */
/* ========================================================================== */
#articlepage-content {
  margin-bottom: 1em;
}
/* ========================================================================== */
#articlepage-content img {
  display: block;
  max-width: 100%;
  margin: 0 auto;
}
#articlepage-content figure img {
  max-width: auto;
  margin: 0;
}

/* Image on the bottom */
/* ========================================================================== */
@media (min-width: 768px) {
  #articlepage-img-bottom {
    max-width: 50%;
    margin: 0 auto;
  }
}

/* Section comment */
/* ========================================================================== */

#articlepage-comments {
  margin-top: 3rem;
}
</style>
