# Theme to use with Sogilis website in 2020 (blog.sogilis.fr)

name = "Sogilis"
license = "MIT"
licenselink = "https://github.com/sogilis/Blog/blob/master/site/themes/sogilis/LICENSE"
description = ""
homepage = "https://sogilis.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Sogilis"
  homepage = "https://sogilis.com/"
