# Theme to use with Sogilis website in 2019 (sogilis.com/fr)

name = "Sogilis"
license = "MIT"
licenselink = "https://github.com/sogilis/Blog/blob/master/site/themes/sogilis/LICENSE"
description = ""
homepage = "http://sogilis.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Sogilis"
  homepage = "http://sogilis.com/"
